# Generated by Django 5.2.8 on 2025-11-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, help_text='Notice image', null=True, upload_to='notices/images/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.FileField(blank=True, help_text='PDF or document attachment', null=True, upload_to='notices/files/'),
        ),
    ]
