# Generated by Django 5.2.8 on 2025-11-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_notice_image_alter_notice_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Upload college logo', upload_to='logo/')),
                ('logo_text', models.CharField(default='School of Science & Technology', max_length=100)),
                ('logo_subtext', models.CharField(default='Madan Bhandari Memorial Academy Nepal', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Logo',
                'verbose_name_plural': 'Site Logos',
            },
        ),
    ]
