# Generated by Django 5.2.8 on 2025-11-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sitelogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='specialization',
            new_name='qualification',
        ),
        migrations.AddField(
            model_name='faculty',
            name='website',
            field=models.URLField(blank=True, help_text='Personal or professional website', null=True),
        ),
    ]
