# Generated by Django 5.2.8 on 2025-11-17 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_specialization_faculty_qualification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('BIT', 'Bachelor of Information Technology'), ('AG', 'Bachelor of Science in Agriculture')], max_length=3, unique=True)),
                ('hero_image', models.ImageField(blank=True, help_text='Background image for curriculum page header', null=True, upload_to='curriculum/hero/')),
                ('overview_text', models.TextField(help_text='Program overview description')),
                ('duration', models.CharField(default='4 Years / 8 Semesters', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Curriculum Page',
                'verbose_name_plural': 'Curriculum Pages',
            },
        ),
        migrations.CreateModel(
            name='CareerProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Career title', max_length=200)),
                ('icon', models.CharField(default='fas fa-briefcase', help_text='Font Awesome icon class', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_prospects', to='home.curriculum')),
            ],
            options={
                'verbose_name': 'Career Prospect',
                'verbose_name_plural': 'Career Prospects',
                'ordering': ['curriculum', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField(help_text='Semester number (1-8)')),
                ('description', models.TextField(blank=True, help_text='Optional semester description', null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='home.curriculum')),
            ],
            options={
                'verbose_name': 'Curriculum Semester',
                'verbose_name_plural': 'Curriculum Semesters',
                'ordering': ['curriculum', 'semester_number'],
                'unique_together': {('curriculum', 'semester_number')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Course code (e.g., BIT101)', max_length=20)),
                ('title', models.CharField(help_text='Course title', max_length=200)),
                ('credits', models.IntegerField(default=3, help_text='Credit hours')),
                ('description', models.TextField(blank=True, help_text='Course description', null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='home.curriculumsemester')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['semester', 'display_order', 'code'],
            },
        ),
    ]
