# Generated by Django 5.2.8 on 2025-11-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_curriculum_careerprospect_curriculumsemester_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['display_order', 'code'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AddField(
            model_name='program',
            name='color_scheme',
            field=models.CharField(choices=[('blue', 'Blue Theme'), ('green', 'Green Theme'), ('purple', 'Purple Theme'), ('red', 'Red Theme'), ('orange', 'Orange Theme'), ('indigo', 'Indigo Theme')], default='blue', help_text='Color theme for program card', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order on homepage'),
        ),
        migrations.AddField(
            model_name='program',
            name='icon_class',
            field=models.CharField(default='fas fa-graduation-cap', help_text='Font Awesome icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='program',
            name='url_slug',
            field=models.SlugField(blank=True, help_text="URL path for curriculum page (e.g., 'bit', 'agriculture')", max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, help_text='Program card image on homepage', null=True, upload_to='programs/'),
        ),
    ]
