# Generated by Django 5.2.8 on 2025-11-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_program_options_program_color_scheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
