# Generated by Django 5.2.8 on 2025-11-18 02:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contactmessage_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('history', 'History'), ('mission', 'Mission & Vision'), ('leadership', 'Leadership Team'), ('facilities', 'Facilities & Infrastructure'), ('achievements', 'Achievements & Awards'), ('accreditation', 'Accreditation & Affiliations'), ('custom', 'Custom Section')], max_length=20)),
                ('title', models.CharField(help_text='Section title', max_length=200)),
                ('content', models.TextField(help_text='Section content')),
                ('image', models.ImageField(blank=True, help_text='Optional section image', null=True, upload_to='about/')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fas fa-history)', max_length=50, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
                'ordering': ['display_order', 'section_type'],
            },
        ),
        migrations.CreateModel(
            name='ImageSlideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Image title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional caption or description', null=True)),
                ('image', models.ImageField(help_text='Slideshow image', upload_to='slideshow/')),
                ('display_location', models.CharField(choices=[('homepage_hero', 'Homepage Hero Section'), ('homepage_gallery', 'Homepage Gallery'), ('programs', 'Programs Page'), ('about', 'About Page'), ('campus', 'Campus Life/Gallery'), ('custom', 'Custom Location')], default='homepage_gallery', help_text='Where to display this image', max_length=20)),
                ('link_url', models.URLField(blank=True, help_text='Optional link when image is clicked', null=True)),
                ('cta_text', models.CharField(blank=True, help_text='Call-to-action button text (for hero slides)', max_length=50, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image Slideshow',
                'verbose_name_plural': 'Image Slideshows',
                'ordering': ['display_location', 'display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='School of Science and Technology', help_text='Full college name', max_length=200)),
                ('short_name', models.CharField(default='SOST', help_text='Short name/acronym', max_length=50)),
                ('tagline', models.CharField(default='Excellence in Education', help_text='College tagline or motto', max_length=300)),
                ('established_year', models.CharField(blank=True, help_text='Year established (e.g., 2010 BS)', max_length=20, null=True)),
                ('about_us', models.TextField(blank=True, help_text='About the college (for About page)', null=True)),
                ('mission', models.TextField(blank=True, help_text='Mission statement', null=True)),
                ('vision', models.TextField(blank=True, help_text='Vision statement', null=True)),
                ('core_values', models.TextField(blank=True, help_text='Core values (one per line)', null=True)),
                ('footer_about', models.TextField(blank=True, help_text='Brief description for footer (max 200 chars recommended)', null=True)),
                ('footer_text', models.CharField(default='© 2025 All rights reserved.', help_text='Copyright text', max_length=200)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for search engines', null=True)),
                ('meta_keywords', models.TextField(blank=True, help_text='Meta keywords (comma separated)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Hero Section Slide', 'verbose_name_plural': 'Hero Section Slides'},
        ),
        migrations.AddField(
            model_name='herosection',
            name='background_overlay',
            field=models.CharField(choices=[('dark', 'Dark Overlay'), ('light', 'Light Overlay'), ('blue', 'Blue Overlay'), ('green', 'Green Overlay'), ('none', 'No Overlay')], default='dark', help_text='Overlay color to make text readable', max_length=20),
        ),
        migrations.AddField(
            model_name='herosection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herosection',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first in carousel'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background image for this slide', null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='cta_link',
            field=models.CharField(blank=True, help_text='Button link URL', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='cta_text',
            field=models.CharField(blank=True, help_text='Call-to-action button text (leave empty to hide button)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.CharField(help_text='Subheading or description', max_length=300),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(help_text='Main heading', max_length=200),
        ),
    ]
