# Generated by Django 5.2.8 on 2025-11-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_aboutsection_imageslideshow_siteconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
