# Generated by Django 5.2.8 on 2025-11-18 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_herosection_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name (e.g., Computer Science)', max_length=100, unique=True)),
                ('short_name', models.CharField(blank=True, help_text='Abbreviation (e.g., CS)', max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='program',
            field=models.ForeignKey(help_text='Program this curriculum belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='home.program'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(help_text='Department name (e.g., Computer Science, Agriculture)', max_length=100),
        ),
    ]
