# Generated by Django 5.2.8 on 2025-11-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_add_department_update_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tab display name (e.g., IT Department, Agriculture Dept.)', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier (e.g., it, agriculture)', unique=True)),
                ('department_filter', models.CharField(help_text='Department name to filter faculty (must match Faculty.department)', max_length=100)),
                ('color_scheme', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange'), ('red', 'Red'), ('indigo', 'Indigo')], default='blue', help_text='Color scheme for this tab', max_length=20)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Faculty Tab',
                'verbose_name_plural': 'Faculty Tabs',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
