# Generated by Django 5.2.8 on 2025-11-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContent',
            fields=[
            ],
            options={
                'verbose_name': 'Footer Content',
                'verbose_name_plural': 'Footer Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.siteconfiguration',),
        ),
    ]
