# Generated by Django 5.2.8 on 2025-11-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_footercontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterContent',
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
