# Generated by Django 5.2.8 on 2025-11-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_delete_footercontent_alter_notice_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Notice', 'verbose_name_plural': 'Notices'},
        ),
        migrations.AddField(
            model_name='event',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notice',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
