# Generated by Django 5.2.8 on 2025-11-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_event_options_alter_notice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['ordering'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['ordering'], 'verbose_name': 'Notice', 'verbose_name_plural': 'Notices'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='display_order',
        ),
        migrations.AddField(
            model_name='event',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='ordering'),
        ),
        migrations.AddField(
            model_name='notice',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='ordering'),
        ),
    ]
