# Generated by Django 5.2.8 on 2025-11-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_event_options_alter_notice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='notice',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
