# Generated by Django 5.2.8 on 2025-11-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_event_ordering_alter_notice_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notice', 'verbose_name_plural': 'Notices'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='ordering',
        ),
    ]
