# Generated by Django 5.2.8 on 2025-11-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_event_options_alter_notice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Notice', 'verbose_name_plural': 'Notices'},
        ),
        migrations.AddField(
            model_name='notice',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
