# Generated by Django 5.2.8 on 2025-11-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='is_spotlight',
            field=models.BooleanField(default=False, help_text='Show this image on homepage spotlight section'),
        ),
    ]
