# Generated by Django 5.2.8 on 2025-11-23 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_galleryimage_is_spotlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Album title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order of display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Album',
                'verbose_name_plural': 'Gallery Albums',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='is_cover',
            field=models.BooleanField(default=False, help_text='Use this image as album cover'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='album',
            field=models.ForeignKey(blank=True, help_text='Album this image belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.galleryalbum'),
        ),
    ]
