# Generated by Django 5.2.8 on 2025-11-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_galleryalbum_galleryimage_is_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile URL', null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL', null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL', null=True),
        ),
    ]
