# Generated by Django 5.2.8 on 2025-11-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_faculty_facebook_url_faculty_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='spotlight_description',
            field=models.TextField(blank=True, default='Capturing moments of creativity, learning, and celebration at MBMAN.', help_text='Description text for spotlight section', null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='spotlight_subtitle',
            field=models.CharField(default='Campus Life', help_text='Small eyebrow title above main title', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='spotlight_title',
            field=models.CharField(default='In the Spotlight', help_text='Main title for spotlight section', max_length=200),
        ),
    ]
