# Generated by Django 5.2.8 on 2025-11-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_siteconfiguration_spotlight_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='map_url',
            field=models.URLField(blank=True, help_text="Google Maps link for 'Visit Us' button", null=True),
        ),
    ]
