# Generated by Django 5.2.8 on 2025-11-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_contactinfo_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='wiki_url',
            field=models.URLField(blank=True, help_text='URL for the Admin Wiki/Documentation (e.g., Gist link).', null=True),
        ),
    ]
