# Generated by Django 5.2.8 on 2025-11-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_siteconfiguration_wiki_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_text',
            field=models.CharField(default='All rights reserved.', help_text="Copyright text (e.g., 'All rights reserved.'). Year and © symbol are added automatically.", max_length=200),
        ),
    ]
