# Generated by Django 5.2.8 on 2025-11-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_siteconfiguration_footer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_text',
            field=models.CharField(default='Madan Bhandari Memorial Academy Nepal. All rights reserved.', help_text="Full copyright text (e.g., 'My College. All rights reserved.'). Year and © symbol are added automatically.", max_length=200),
        ),
    ]
