# Generated by Django 5.2.8 on 2025-11-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_siteconfiguration_footer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(help_text='Enter phone numbers separated by commas (e.g., +977-021-540000, 98520xxxxx)', max_length=100),
        ),
    ]
