# Generated by Django 5.2.8 on 2025-11-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_contactinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='degree_level',
            field=models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Ph.D.', 'Ph.D.')], default='Bachelors', help_text='Level of the degree (e.g., Bachelors, Masters)', max_length=20),
        ),
    ]
