# Generated by Django 5.2.8 on 2025-11-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_program_degree_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='degree_level',
            field=models.CharField(default='Bachelors', help_text='Level of the degree (e.g., Bachelors, Masters, Ph.D.)', max_length=50),
        ),
    ]
