# Generated by Django 5.2.8 on 2026-01-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_program_degree_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumsemester',
            name='syllabus_file',
            field=models.FileField(blank=True, help_text='Upload PDF syllabus for this semester', null=True, upload_to='syllabus/'),
        ),
    ]
