# Generated by Django 5.2.8 on 2026-01-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_curriculumsemester_syllabus_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryalbum',
            name='date_bs',
            field=models.CharField(blank=True, help_text='Date in Bikram Sambat', max_length=50, null=True),
        ),
    ]
